show databases;
create database gram_panchayath_db;
use gram_panchayath_db;
create table citizen (citizen_id int primary key , full_name varchar(100) not null, date_of_birth date not null ,gender varchar(10) not null , mobile_number varchar(50) unique not null , occupation varchar(50) , village_name varchar(50) not null , is_active boolean not null );
create table certificate_type (certificate_type_id int primary key , certificate_name varchar(50) not null unique, description varchar(200) not null , processing_days int not null , application_fees decimal(8,2) not null , is_available boolean not null );
create table certificate_application(appliction_id int primary key , citizen_id int not null , certificate_name varchar(100) not null , application_date date not null , purpose varchar(200) not null, application_status varchar(30) not null, fee_paid decimal(8,2) not null , reference_number varchar(30) unique not null );
create table panchayat_office(office_id int primary key, office_name varchar(100) not null , village_name varchar(50) not null , pincode varchar(6) not null, contact_number varchar(15) unique , office_email varchar(100) unique , opening_time time not null , is_operational boolean not null );
show tables;
insert into citizen(citizen_id,full_name,date_of_birth,gender,mobile_number,occupation,village_name,is_active) values(101,'Ravi Kumar','1995-06-15','Male','9876500001','Farmer','Ramapuram',TRUE),(102,'Lakshmi Devi','1995-11-22','Female','9876500002','Tailor','Ramapuram',TRUE),(103,'Suresh Babu','1992-03-10','Male','9876500003','shopkeper','seethampeta',TRUE),(104,'Anjali Rao','2000-08-05','Female','9876500004','Student','Ramapuram',TRUE),(105,'Kiran Kumar','2000-01-18','Male','9876500005','Electrician','seethapuram',TRUE),(106,'Meena Kumari','1998-12-30','Female','9876500006','Teacher','Lakshmipuram',FALSE);
insert into certificate_type(certificate_type_id,certificate_name,description,processing_days,application_fees,is_available) values (1,'Residence Certificate','Certifies the declared place of residence',7,30.00,TRUE),(2,'Birth Record Request','Request for a locally maintained birth record',5,20.00,TRUE),(3,'Death Record Request','Request for locally maintained death record',5,20.00,TRUE),(4,'Family Member Certifiacte','Records Declared family member information',10,40.00,TRUE),(5,'Property Certificate','Certificate related to locally maintained property records',15,50.00,TRUE),(6,'No-Dues Certificate ', 'Indicates applicable local dues status',7,25.00,FALSE);
insert into certificate_application(appliction_id,citizen_id,certificate_name,application_date, purpose,application_status,fee_paid,reference_number) values (1001,101,'Residence Certificate','2026-07-01','Bank account documentaion','submitted',30.00,'GP20260001'),(1002,102,'Family Member Certificate','2026-07-02','Welfare Scheme application','Under Review',40.00,'Gp20260002'),(1003,103,'Property Certificate','2026-07-03','Property documentation','submitted',50.00,'GP20260003'),(1004,104,'Residence Certificate','2026-07-04','College admission','Approved',30.00,'GP20260004'),(1005,105,'No-Dues Certificate','2026-05-05','Local service requirement','Under Review',25.00,'GP20260005'),(1006,106,'Birth Record Request ', '2026-07-06','Personal documentation','Rejected',20.00,'GP20260006');
insert into panchayat_office(office_id,office_name,village_name,pincode,contact_number,office_email ,opening_time,is_operational ) values (1,'Ramapuram Gram Panchayat','Ramapuram','521101','0866000001','ramapuram@gp.example','09:00:00',true),(2,'seethampeta Gram Panchayat','Seethampeta','521102','0866000002','seethampeta@gp.example','09:30:00',true),(3,'Lakshmipuram Gram Panchayat','Lakshmipuram','521103','0866000003','lakshmipuram@gp.example','09:00:00',true),(4,'Krishnapuram Gram Panchayat','Krishnapuram','521104','0866000004','Krishnapuram@gp.example','10:00:00',true),(5,'Venkatapuram Gram Panchayat','Venkatapuram','521105','0866000005','Venkatapuram@gp.example','09:30:00',true),(6,'Gopalapuram Gram Panchayat','Gopalapuram','521106','0866000006','Gopalapuram@gp.example','09:00:00',false);
select *from citizen;
select *from certificate_type;
select *from certificate_application;
select *from panchayat_office;
insert into `citizen` (`citizen_id`, `full_name`, `date_of_birth`, `gender`, `mobile_number`, `occupation`, `village_name`, `is_active`) values ('107', 'Hemanth Kumar', '2007-11-29', 'Male', '8466819318', 'Student', 'Patha Bitragunta', true);
insert into `certificate_type` (`certificate_type_id`, `certificate_name`, `description`, `processing_days`, `application_fees`, `is_available`) values ('7', 'Income Certificate', 'Certifies the family or individual income for annual', '5', '100000', true);
update certificate_application set application_status='Under Review' where (appliction_id=1001);
update certificate_application set application_status='Approved' where (appliction_id=1002);
update citizen set occupation='Electrical Technican' where (citizen_id=105);
update certificate_type set processing_days=12 where (certificate_type_id=5);
update certificate_type set is_available=true where (certificate_type_id=6);
delete from citizen where citizen_id=107;
alter table citizen add address varchar(100) ;
alter table certificate_application add issued_date varchar(20) ;
alter table certificate_application modify purpose varchar(250);
alter table panchayat_office add closing_time time;
create table temporary_request(request_id int primary key , request_name varchar(20) not null, request_date date not null);
select *from temporary_request;
INSERT INTO `gram_panchayath_db`.`temporary_request` (`request_id`, `request_name`, `request_date`) VALUES (1, 'venkatesh', '2026-07-20'),(2, 'Hemanth','2026-07-20'),(3,'Tharun','2026-07-20');
truncate temporary_request;
drop table temporary_request;
insert into `citizen` (`citizen_id`, `full_name`, `date_of_birth`, `gender`, `mobile_number`, `occupation`, `village_name`, `is_active`) values ('101', 'Hemanth Kumar', '2007-11-29', 'Male', '8466819318', 'Student', 'Patha Bitragunta', true);
insert into `citizen` (`citizen_id`, `full_name`, `date_of_birth`, `gender`, `mobile_number`, `occupation`, `village_name`, `is_active`) values ('107', 'Hemanth Kumar', '2007-11-29', 'Male', '9876500001', 'Student', 'Patha Bitragunta', true);
insert into `certificate_type` (`certificate_type_id`, `description`, `processing_days`, `application_fees`, `is_available`) values ('7', 'Certifies the family or individual income for annual', '5', '100000', true);
insert into certificate_application(appliction_id,citizen_id,certificate_name,application_date, purpose,application_status,fee_paid,reference_number) values (1008,108,'Residence Certificate','2026-07-01','Bank account documentaion','submitted',30.00,'GP20260001');
