show databases;
use gram_panchayath_db;
show tables;
select *from citizen;
select *from certificate_type;
select *from certificate_application;
select *from panchayat_office;
select upper(full_name) as UPPER_CASE from citizen ;
select lower(village_name) as lower_case from citizen;
select length(full_name) as Length from citizen;
select substring(reference_number,1,4) as reference_number from certificate_application;
select concat(full_name,' - ',village_name) as full_name__village_name from citizen;
select replace(certificate_name,'Certificate','Cert .') from certificate_type;
select trim(certificate_name) as removing_spaces from certificate_type;
select left(full_name,instr(full_name,' ')) as first_name from citizen;
select concat('Citizen :',full_name ,"\n", 'Village :',village_name ) as details from citizen;
select *from certificate_application where left(reference_number,6)='GP2026' ;
select round(application_fees) as fees from certificate_type;
select abs(processing_days-10) as dispaly from certificate_type;
select sqrt(processing_days) as square_root from certificate_type;
select mod(processing_days,3) as diplay from certificate_type;
select round(application_fees,1) as dispaly from certificate_type;
select ceil(application_fees) as dispaly_ceiling ,floor(application_fees) as display_floor from certificate_type;
select rand()*100 as random_number;
select power(processing_days,2) as square from certificate_type;
select processing_days*2 as 2_multiple from certificate_type;
select curdate() as todays_date;
select current_date(),current_time()as date_time;
select year(application_date) as application_year from certificate_application;
select month(application_date) as application_month from certificate_application;
select day(application_date) as application_day from certificate_application;